language: node_js
node_js:
    - 8.0.0

addons:
    chrome: stable

dist: trusty

cache:
    directories:
        - "node_modules"

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - npm i -g npm@latest
 - npm i -g @angular/cli@1.0.4
 - npm i -g karma

script:
    - karma start karma.conf.js --single-run
